[package]
name = "columbo"
version = "0.1.0"

edition = "2024"

[dependencies]
bytes = "1.11.1"
futures = "0.3"
tokio = { version = "1", features = [ "rt", "sync" ] }
tokio-stream = "0.1"
ulid = "1"

[dev-dependencies]
axum = { version = "0.8", features = [ "macros" ] }
maud = "0.27"
tokio = { version = "1", features = [ "full" ] }
